Repository Elbions/barber-shop, pull requests merged in 2022-02, with the labels that each got.

#3 feat: creating develop branch and input style
  barber-shop/src/App.tsx
  barber-shop/src/assets/icons/imgemail.png
  barber-shop/src/assets/icons/imgpassword.png
  barber-shop/src/components/input/input.module.scss
  barber-shop/src/components/input/input.tsx
Labels: principal, precisa de atenção

#11 feat: creating routes and the structure to login page
  barber-shop/package-lock.json
  barber-shop/package.json
  barber-shop/src/App.tsx
  barber-shop/src/pages/login/login.module.scss
  barber-shop/src/pages/login/login.tsx
  barber-shop/src/routes/routes.js
Labels: principal, precisa de atenção

#12 Release/20220202
  barber-shop/package-lock.json
  barber-shop/package.json
  barber-shop/src/App.tsx
  barber-shop/src/pages/login/login.module.scss
  barber-shop/src/pages/login/login.tsx
  barber-shop/src/routes/routes.js
Labels: release

#13 Feat/bs 02 creating input component styles
  barber-shop/src/assets/icons/logo.png
  barber-shop/src/components/input/input.module.scss
  barber-shop/src/components/input/input.tsx
  barber-shop/src/pages/login/login.tsx
Labels: principal

#14 Feat/bs 01 creating button component structure
  barber-shop/src/components/button/button.module.scss
  barber-shop/src/components/button/button.tsx
  barber-shop/src/pages/login/login.tsx
  barber-shop/yarn.lock
Labels: principal

#15 release/20220203
  barber-shop/src/assets/icons/logo.png
  barber-shop/src/components/button/button.module.scss
  barber-shop/src/components/button/button.tsx
  barber-shop/src/components/input/input.module.scss
  barber-shop/src/components/input/input.tsx
  barber-shop/src/pages/login/login.tsx
  barber-shop/yarn.lock
Labels: release

#16 Feat/bs 05 login page structure
  barber-shop/src/assets/icons/imgregister.png
  barber-shop/src/components/button/button.module.scss
  barber-shop/src/components/input/input.module.scss
  barber-shop/src/pages/login/login.module.scss
  barber-shop/src/pages/login/login.tsx
  barber-shop/src/styles/reset.scss
Labels: principal

#17 Release/20220205
  barber-shop/src/pages/login/login.module.scss
  barber-shop/src/pages/login/login.tsx
Labels: release
